language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  include:
    - php: 5.6
      env: NETTE_VERSION='2.2.*'

install:
  - wget https://raw.githubusercontent.com/Zenify/CI/master/travis/coverage-init.sh && sh coverage-init.sh
  - sh -c 'if [ "$NETTE_VERSION" != "" ]; then composer require --no-update nette/nette=$NETTE_VERSION; fi;'
  - composer install --prefer-source

before_script:
  - wget https://raw.githubusercontent.com/Zenify/CI/master/travis/static-analysis.sh && sh static-analysis.sh

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - wget https://raw.githubusercontent.com/Zenify/CI/master/travis/coverage-send.sh && sh coverage-send.sh
